### ISSUE TITLE
Ability to Filter Out Devices

### ISSUE THREAD

**Issue by conallob** [hassio-addons/addon-airsonos#107]
I have 7 Sonos devices of various different vintages. 3 devices are new enough to support AirPlay 2 natively, but they are also discovered by AirSonos.

This results in a very long list of 10+ AirPlay devices, which causes UX issues.

Would it be possible to add the ability to blacklist a device (by name, IP or MAC address are all equally good options) via configuration please?

Thank you for developing this add on, it greatly improves my Sonos system

**Comment by frenck** [comment]
You can do that already using the `airsonos.xml` configuration file. You can the `enabled` option in that file for devices you don't want to `0`.

https://github.com/hassio-addons/addon-airsonos/blob/main/airsonos/DOCS.md#tweaking-airsonos
