### ISSUE TITLE
AirSonos not picking up Sonos intergrations from a Remote Home Assistant

### ISSUE THREAD

**Issue by fossie08** [hassio-addons/addon-airsonos#123]
# Problem/Motivation

>I have two home assistant instances each on their own networks with different routers and everything and connected together by home assistant remote.
On one instance I have 3 Sonos boxes connected and it is running Home Assistant containerised. On the other, I have one connected.
The instance that has 3 boxes is the remote node.

## Expected behavior

> I would like to see all 4 boxes on either network and to stream to any on them no matter of which network I am connected to.

## Actual behavior

> I can see all 4 boxes on the master instance - one with one sonos connected - and AirSonos is displaying that one Sonos but not the other 3.
I cannot see any of the Sonos boxes on the remote node as an airplay receiver.

## Steps to reproduce

> Two home assistant instances on two different networks connected by home assistant remote with Sonos boxes integrations added and one of the home assistant instances running AirSonos

## Proposed changes

> allow the discovery of Sonos intergrations inside of AirSonos

**Comment by frenck** [comment]
This add-on does not limit or actively disregard any (regardless of their source).

If they don't do up, it means that mDNS (multicast traffic) isn't coming through (which is expected, this generally requires extra configurations between networks).

Closing this issue, as this is not a limitation of the addon.

../Frenck
