### ISSUE TITLE
Not able to start AirSonos

### ISSUE THREAD

**Issue by projectraam** [hassio-addons/addon-airsonos#13]
I am not able to starts AirSonos and the it does not add anything in the logs. I have tried to uninstall and install again. 

## Expected behavior
AirSonos will start and I am able to see something in the logs

## Actual behavior
The start button turns red and I can't see anything in the logs, it is completely empty. 

## Steps to reproduce

I am running Hass.io version 0.95.4

I have installed AirSonos version 2.1.0

**My AirSonos config**
{
  "address": "",
  "port": 49152,
  "latency_rtp": 1000,
  "latency_http": 2000,
  "drift": false,
  "log_level": "trace"
}

**Comment by frenck** [comment]
Please take a look at the supervisor logs. If it turns read immediately, it should show up there.

**Comment by projectraam** [comment]
Thanks for helping frenck. I tried to check the supervisor logs and it gives me this error 

`ERROR (SyncWorker_1) [hassio.docker] Can't start addon_a0d7b954_airsonos: 403 Client Error: Forbidden ("endpoint woth name addon_a0d7b954_airsonos already exists in network host")`

**Comment by projectraam** [comment]
Does any body know how to delete addon_a0d7b954_airsonos from the network host? I have tried to uninstall, but that did not help.

**Comment by frenck** [comment]
That sounds like a Hass.io issue and out of control for the add-on.
Please report this there.
