### ISSUE TITLE
Sonos speaker didn't work with Airsonos/airconnect anymore

### ISSUE THREAD

**Issue by Delta1977** [hassio-addons/addon-airsonos#134]
As desicribed here Sonos change something in latest firmware

https://github.com/philippe44/AirConnect/issues/458

Workaround is to send audio as wav or mp3 instead of flac. 

Can you build in the parameter -c wav to your image or make it to an configuration item in addon ? 

Thanks

**Comment by chucklebrother** [comment]
Not that I know much about this project, or how dicker works, but I think you might be able to update the line here:

https://github.com/hassio-addons/addon-airsonos/blob/2fd4ea421dc7c6b5110ef42bd6c1507a53d8f8e8/airsonos/rootfs/etc/airsonos.xml#L7

Change from "pcm" to "wav".

Note! The default is FLAC, which is what the comments and advice in https://github.com/philippe44/AirConnect/issues/458 concern themselves with, I havent ever used PCM to stream using Airconnect/Airupnp, so I can;t comment on if it has _ever_ worked, however, I did some testing, and PCM fails to stream, wheras, as noted in the other issue, WAV works as expected.

**Comment by mattsheffiel** [comment]
Changing the codec to wav in the config file worked for me as well. Thanks @chucklebrother!

**Comment by Delta1977** [comment]
Thanks for help. Edit config/airsonos.xml helps me.
