### ISSUE TITLE
AirSonos starts but the app is not added to the HASSIO menu.

### ISSUE THREAD

**Issue by funxiun** [hassio-addons/addon-airsonos#140]
# Problem/Motivation
AirSonos starts but the app is not added to the HASSIO menu.

## Expected behavior
Add-on added to the HASSIO screen and add-on can be controlled.

## Actual behavior
Toggle switches (auto startup, watchdog and auto update) go to disabled state after clicking on start.

Looking at the logfiles AirSonos was started (and works too) but the add-on screen doesn't say so.
Restarted the HA core a few times but that didn't do the trick.

Plug-in version: 3.5.4 
Home Assistant 2023.5.3 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend-version: 20230503.3 - latest

**Comment by funxiun** [comment]
Hi Frenck

I'm sorry if things make no sense but I was referring to this screen:
![Screenshot from 2023-05-22 11-31-02](https://github.com/hassio-addons/addon-airsonos/assets/32570446/4f0598e0-9b08-4e67-bba5-7ac7f089eaf4)

Are you trying to say that these toggle switches have no use in the add-in?

**Comment by frenck** [comment]
Those are not provided by this add-on, you are reporting an issue with Home Assistant to an add-on repository.

../Frenck
