### ISSUE TITLE
CastSonos / CastAir?

### ISSUE THREAD

**Issue by Royal2000H** [hassio-addons/addon-airsonos#15]
Hi, sorry if this is too off-topic. But perhaps this is something that is a possibility or possibly worked on.

You created AirSonos (Airplay -> Sonos) and AirCast (Airplay -> Chromecast). How about CastSonos/CastAir, i.e. Chromecast -> Sonos and/or Chromecast -> Airplay.

For those of us with Android devices, we do not have built in airplay but do have Cast built-in. And then I have sonos devices on my network (that also accept Airplay) so it would be nice to be able to cast to them.

**Comment by frenck** [comment]
We can't. The protocol hasn't been reversed engineered.

**Comment by Royal2000H** [comment]
Thanks for your response. Which protocol is that in reference to? Cast or Sonos or Airplay?
