### ISSUE TITLE
AirPlay 2

### ISSUE THREAD

**Issue by danlun** [hassio-addons/addon-airsonos#18]
# Problem/Motivation
Does this support AirPlay 2 or only AirPlay?
> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
If not, can it be requested?
> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Add-ons wrap existing applications. The application used does not support it.
