### ISSUE TITLE
clarification for option 'address'

### ISSUE THREAD

**Issue by Lebernd** [hassio-addons/addon-airsonos#19]
# Problem/Motivation

> I've opened a issue some time ago about a problem which was a result of misunderstanding the docs

## Expected behavior

> read the docs and understand what is meant

## Actual behavior

> misunderstud and error on startup that couldn't get solved

## Steps to reproduce

> Put sonos ip in the config. Search the internet for solutions, create issue etc. 

## Proposed changes

add something like: 
`(not your Sonos device) ` to the docs in this section.
The first sentence would be:
```
This option allows you to specify the IP address the AirSonos server needs to
bind to (not your Sonos device).
```

Best, Bernd

**Comment by frenck** [comment]
Sorry, this is about binding, not connecting, secondly, it states this is about the AirSonos server.

**Comment by Lebernd** [comment]
You are of course right. I wouldn't have even proposed it, if it was just for me. But when you actually scroll through https://community.home-assistant.io/t/home-assistant-community-add-on-airsonos/36796 - you will find other people stumbled across this network address setting.
After understanding the setting it is obvious, that the airsonos server is meant and not the sonos device, that it is about binding and not connecting.
