### ISSUE TITLE
Permission denied after 0.3.0 update

### ISSUE THREAD

**Issue by pallazola** [hassio-addons/addon-airsonos#2]
After updating airsonos to 3.0.0 the server can't start. I get the following error in the log:

INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied

This is running on hass.io, so Airsonos is running in it own docker container. I have no special config, this is a stock install from the hass.io add on store.

full log:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: AirSonos v0.3.0

 AirPlay capabilities for your Sonos (and UPnP) devices.

 From: Community Hass.io Add-ons
 By: Franck Nijhof <frenck@addons.community>
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 03-version-requirements.sh: executing... 

[cont-init.d] 03-version-requirements.sh: exited 0.
[cont-init.d] 50-airsonos.sh: executing... 
[cont-init.d] 50-airsonos.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied
INFO: Starting the AirSonos server
./run: line 49: /usr/bin/airsonos: Permission denied`

**Comment by pallazola** [comment]
ok so I made airsonos executable and it fixed the problem (chmod +x /usr/bin/airsonos)

**Comment by frenck** [comment]
Sorry about this, I've corrected the error and released version 0.3.1 to address this.
