### ISSUE TITLE
Speakers and server on different networks

### ISSUE THREAD

**Issue by embcla** [hassio-addons/addon-airsonos#20]
# Problem/Motivation

AirSonos doesn't find the speakers

## Expected behavior

that it found my speakers

## Actual behavior
nothing happens

So basically my server is on 192.168.101.x while the speakers are on 192.168.103.x and the module doesn't seem to be able to find the sonos(es).
They are in my homeassistant config, and HA can control them fine.
If it can't use the Sonos entities, can I tell it to explicitly look for certain IPs?

## Steps to reproduce

Put the sonos on a different subnet than the server

**Comment by frenck** [comment]
That is not possible with this add-on.
