### ISSUE TITLE
After upgrade to 2.4.0, stops working

### ISSUE THREAD

**Issue by ChrisHardie** [hassio-addons/addon-airsonos#22]
# Problem/Motivation

After my Home Assistant install updated this addon to 2.4.0, it stopped working.

## Expected behavior

To be able to play audio via AirPlay on Sonos devices.

## Actual behavior

Sonos devices show up as available for audio, but attempts to actually stream sound to them result in a "can't connect" error. 

Logs don't indicate any problems:

```
[14:24:26] INFO: Starting the AirSonos server...
[14:24:29.880664] main:1390 Starting airupnp version: v0.2.28.2 (Oct 24 2020 @ 13:37:03)
[14:24:29.935223] Start:1108 Binding to 192.168.1.80:49152
[14:24:30.197070] AddMRDevice:992 [0xb2b89008]: adding renderer (Kitchen)
[14:24:30.209630] MasterHandler:656 [0xb2b89008]: subscribe success
```

but the UI is not so happy:

<img width="421" alt="Screen Shot 2020-10-26 at 14 30 05" src="https://user-images.githubusercontent.com/311772/97213298-cf477780-1797-11eb-848c-a09ddcc50435.png">

## Steps to reproduce

On iOS or Mac OS, attempt to connect to a Sonos device made available through this addon. Start playing music/sound and receive an error.

## Proposed changes

I have not yet tried downgrading but that's my next course of action.

**Comment by bwohlgamuth** [comment]
Seeing the same issue on my system. Attempted add/remove of add on and restart of host system (pi)

**Comment by gmahidhar79** [comment]
I am having the same issues as well, it is connecting to the device but when I start playing music it says couldnt connect to the device

**Comment by bwohlgamuth** [comment]
@ChrisHardie - you mention rolling back to a previous version, would you be able to link to instructions for how to accomplish that?

**Comment by ChrisHardie** [comment]
> @ChrisHardie - you mention rolling back to a previous version, would you be able to link to instructions for how to accomplish that?

I'm brand new to HA and addon management but if I figure it out I will let you know. :) I was assuming there would be a way via CLI, but just found that the `ha addons update` command does not support version targets, and even explicitly says "It is currently not possible to upgrade/downgrade to a specific version."

It seems like there would be a way to upload a specific release of an addon, but I haven't found it yet. The next best thing I can think of is to fork this addon repository, revert to the previous version, and then point Supervisor to it as [a new add-on repository](https://developers.home-assistant.io/docs/add-ons/repository), but that feels pretty cumbersome as a temporary workaround.

**Comment by bwohlgamuth** [comment]
@frenck any chance of reverting the breaking change here?

**Comment by helmuto-maker** [comment]
I believe I have the same issue. Sonos zones show up fine and attach in airplay on iPhone, but when I start playback I get this warning. Think is started with 2.4.0.

> 
> 
> I am having the same issues as well, it is connecting to the device but when I start playing music it says couldnt connect to the device

Same here. Attaches via airplay to Sonos Zones, but errors when playback is starting.

**Comment by frenck** [comment]
Problem is known, hope to find time for a fix soon.
In the meantime, you can restore a previous snapshot to rollback.

**Comment by helmuto-maker** [comment]
Hi Frank - thanks for getting back to me. Can I rollback just the airsonos
part ? Best Mads

**Comment by AndyMcSchopf** [comment]
Had the same problem - backup from snapshot (you can choose what to restore) brought back the working 2.3.2 version

**Comment by helmuto-maker** [comment]
It worked to downgrade selectively the Airsonos to 2.3.2 - very nice.
Thanks for the help !

**Comment by frenck** [comment]
⬆️ AirSonos v2.4.1

https://github.com/hassio-addons/addon-airsonos/releases/tag/v2.4.1
