### ISSUE TITLE
./run: line 49: /usr/bin/airsonos: Permission denied

### ISSUE THREAD

**Issue by artistan82** [hassio-addons/addon-airsonos#3]
# Problem/Motivation

> /usr/bin/airsonos fails to start.

## Expected behavior

> /usr/bin/airsonos to start when starting addon-airsonos.

## Actual behavior

> INFO: Starting the AirSonos server
> ./run: line 49: /usr/bin/airsonos: Permission denied

## Steps to reproduce

> Update to latest v.0.3.0

## Proposed changes

> Permission for /usr/bin/airsonos is set to -rw-rw-r--.
> This should be set top -rwxrwxr-x instead.

**Comment by artistan82** [comment]
Found issue was already submitted and closed.

**Comment by frenck** [comment]
Sorry about this, I've corrected the error and released version 0.3.1 to address this.
