### ISSUE TITLE
Segfaults on Raspberry Pi 1.

### ISSUE THREAD

**Issue by leenooks** [hassio-addons/addon-airsonos#4]
# Problem/Motivation

Your container doesnt run on a Raspberry Pi 1 - it segfaults.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
[cont-init.d] 00-banner.sh: exited 267.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
s6-maximumtime: warning: child process crashed
[cont-finish.d] 99-message.sh: exited 111.
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
```

When running the container manually `docker run -it --rm --entrypoint=/bin/sh hassioaddons/airsonos-armhf`, it exits 139 (segault inside container)

I've even tried to add to your image, but the build fails 

```Dockerfile
FROM hassioaddons/airsonos-armhf:0.3.1

RUN apt-get update && apt-get install bash
```

```Build
root@hassio:/tmp# docker build -t test .
Sending build context to Docker daemon  6.656kB
Step 1/2 : FROM hassioaddons/airsonos-armhf:0.3.1
 ---> 0737d267e0c1
Step 2/2 : RUN apt-get update && apt-get install bash
 ---> Running in 6fee22d9787e
The command '/bin/sh -c apt-get update && apt-get install bash' returned a non-zero code: 139
```

Happy to help try and debug this, but I'd need your help - I'm new to hass.io and resin.io :(

**Comment by leenooks** [comment]
No, still the same thing - it exits with 139 (SEGFAULT).

I think the problem is due to the base image - I dont think it is suitable for a Raspberry Pi 1?

I tested hassioaddons/debian-base-armhf and it segfaults. However, if I use hassioaddons/base-armhf it doesnt. So if this app is based on the debian-base-armhf image as base - then that is probably the reason?

**Comment by frenck** [comment]
True, you are absolutely right.
The base image changed to Ubuntu this release, nevertheless, is is ARMv7.
The Pi 1 and Zero are ARMv6 based.

This is not a thing I can workaround at this moment.
Alpine is missing GLibc, which is required for this add-on :(

**Comment by frenck** [comment]
This needs to be documented.

**Comment by leenooks** [comment]
Does this help? https://github.com/leannenorthrop/rpi-alpine-glibc

**Comment by frenck** [comment]
Well @leenooks, that things is unmaintained. 

There are some "third-party" libs I could use, nevertheless, I'm kinda holding back on that kind of things... They have the bad habit to fire back eventually...

**Comment by frenck** [comment]
@leenooks I've looked into this again.
There are glibc's that are up to date, but then again, they are not cross-platform (so that is a problem).
Secondly, AirConnect required OpenSSL 1.0.0 branch, which is not available for Alpine as well.

So, that makes 2 blocking issue for moving this add-on to the Alpine base. 

I feel like there is no option left me, but adding a known issue note to the documentation.

**Comment by frenck** [comment]
I've added a **Known issues and limitations** section to the documentation, covering this.

Thank you for reporting. I'm sorry I can't offer a proper solution for this.
