### ISSUE TITLE
AirSonos Continuously Restarting on HassOS

### ISSUE THREAD

**Issue by jpreiditsch** [hassio-addons/addon-airsonos#6]
# Problem/Motivation

The AirSonos server does not start, it continually gets stuck in a starting looping. This causes the CPU to spike.

## Expected behavior

Service starts

## Actual behavior

 
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server
INFO: Starting the AirSonos server

## Steps to reproduce

Install AirSonos on HassOS, start it.

## Environment
HomeAssistant 73.1
Hass.io supervisor 115
Host System HassOS 1.5

**Comment by frenck** [comment]
Probably related to: hassio-addons/aircast#9

**Comment by frenck** [comment]
Should be fixed now. Tested on HassOS as well.

**Comment by jpreiditsch** [comment]
Thank you!
