### ISSUE TITLE
Devices discovered but no seein in HA

### ISSUE THREAD

**Issue by jbega** [hassio-addons/addon-airsonos#67]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by jbega** [comment]
Hello.
Also install your aircast addon.
After installing the airsonos addon, in the registry I see that it detects two devices (a tv and a speaker) but then in the HA media player they are not able to select and send audio as if the chromecast added through the aircast addon , am I doing something wrong or am I misunderstanding the concept?
Thanks

**Comment by frenck** [comment]
It has nothing to do with Home Assistant? It's a bridge for cast devices to airplay for audio.

**Comment by jbega** [comment]
Thanks for answering! Sorry but I don't understand you (maybe because of the translations)
It has nothing to do as a home assistant? Isn't this addon for home assistant?

This is precisely what I am trying to do ... send music to my airplay devices (from home assistant).

**Comment by frenck** [comment]
Sure, addons runs additional applications in the ecosystem, they don't have to integrate to be valuable.
