### ISSUE TITLE
Exclude speakers

### ISSUE THREAD

**Issue by pallazola** [hassio-addons/addon-airsonos#7]
Is there any way to exclude speakers from detection? With the introduction of Airplay 2 I would like to be able to choose which speakers to use with AirSonos (exclude the newer Airplay 2 compatible speakers leave the older speakers for AirSonos) .
Thanks,
Mike

**Comment by frenck** [comment]
Speakers can now be excluded in v0.6.0, using custom configuration file tweaking.
